---
- name: ensure sudo is installed on debian
  apt: pkg=sudo state=installed
  when: ansible_os_family == 'Debian'
  tags: ["packages","sudo"]

- name: ensure sudo is installed on redhat
  yum: name=sudo state=present
  when: ansible_os_family == 'RedHat'
  tags: ["packages","sudo"]

- name: ensure sudo is installed on suse
  zypper: name=sudo state=present
  when: ansible_os_family == 'SUSE'
  tags: ["packages","sudo"]

- name: ensure sudoers.d directory is present
  file: path=/etc/sudoers.d owner=root group=root mode=0750 state=directory
  tags: ["configuration","sudo"]

- name: ensure configuration of additionals sudoers file
  template: src=additional.j2 dest=/etc/sudoers.d/{{item.name}} mode=0440 owner=root group=root validate='/usr/sbin/visudo -cf %s'
  with_items: "{{sudo_file}}"
  tags: ["configuration","sudo"]

- name: ensure configure of sudoers base file
  template: src=sudoers.j2 dest=/etc/sudoers mode=0440 owner=root group=root validate='/usr/sbin/visudo -cf %s'
  tags: ["configuration","sudo"]

